const skills = [
  'Microsoft Word',
  'Microsoft Excel',
  'Microsoft PowerPoint',
  'JavaScript',
  'Python',
  'HTML5',
  'CSS3',
  'Adobe Photoshop',
  'SQL',
  'Git',
  'Node.js',
  'React',
  'PostgreSQL',
  'Java',
  'C++',
  'AutoCAD',
  'MATLAB',
  'Google Analytics',
  'Figma',
  'Canva',
  'Next.js',
  'Sequelize',
  'Docker',
  'Kali Linux',
  'Bash',
  'TypeScript',
  'Visual Studio Code',
  'Notion',
  'Linux',
  'Firebase',
  'Microsoft Access',
  'SAP',
  'Prezi',
  'SPSS',
  'Tableau',
  'Slack',
  'Zoom',
  'Salesforce',
  'Trello',
  'Asana',
  'Zendesk',
  'QuickBooks',
  'Google Sheets',
  'Power BI',
  'WordPress',
  'Scrum',
  'Agile Methodologies',
  'JIRA',
  'CRM Management',
  'Data Entry',
  'Microsoft Outlook',
  'Blender',
  'Audacity',
  'Final Cut Pro',
  'Illustrator',
  '3D Modeling',
  'Google Drive',
  'Data Visualization',
  'Technical Writing',
  'Video Editing',
  'Adobe After Effects',
  'Statistical Analysis',
  'Public Speaking',
  'Customer Relationship Management (CRM)',
  'SEO (Search Engine Optimization)',
  'SEM (Search Engine Marketing)',
  'Email Marketing',
  'Content Creation',
  'Cloud Computing',
  'Cybersecurity',
  'Virtualization (VMware, Hyper-V)',
  'Network Configuration',
  'IT Support',
  'Digital Marketing',
  'Project Management',
  'Event Planning',
  'Conflict Resolution',
  'Financial Analysis',
  'Legal Research',
  'Human Resources Management',
]
